apiVersion: v1
kind: Service
metadata:
  name: {{ include "isambard.fullname" . }}-browser
  labels:
    {{- include "isambard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.browser.type }}
  selector:
    {{- include "isambard.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.browser.port }}
      targetPort: http-browser
